FROM php:8.4-fpm-bookworm

RUN apt-get update && apt-get install -y \
    nginx \
    supervisor \
    git \
    unzip \
    curl \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libzip-dev \
    libicu-dev \
    libonig-dev \
    libxml2-dev \
    default-mysql-client \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install \
        pdo_mysql \
        mbstring \
        exif \
        pcntl \
        bcmath \
        gd \
        zip \
        intl \
    && rm -rf /var/lib/apt/lists/*

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

COPY composer.json composer.lock ./

RUN composer install \
    --no-dev \
    --no-interaction \
    --prefer-dist \
    --optimize-autoloader \
    --no-scripts

COPY package.json package-lock.json ./

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && npm ci

COPY . .

RUN npm run build

# The host checkout contains bootstrap/cache/{packages,services}.php generated by
# a `composer install` that INCLUDED require-dev packages (laravel/boost,
# laravel/pail, laravel/sail, nunomaduro/collision). This image installs with
# --no-dev, so those providers are not present in vendor/. Baking the host
# manifests in makes Application::registerConfiguredProviders() attempt to
# register Laravel\Boost\BoostServiceProvider and abort with a fatal
# "Class ... not found" before routing ever runs. Purge them and let Composer
# rebuild the manifest from the --no-dev dependency set that is actually here.
RUN rm -f bootstrap/cache/*.php \
    && rm -f bootstrap/cache/config.php bootstrap/cache/routes-*.php \
    && composer dump-autoload --no-dev --optimize --no-interaction

# `artisan storage:link` was run on the host, so public/storage is a symlink to
# an absolute path outside this image (/home/...). It resolves to nothing here
# and every storage/ asset 404s. Recreate it against the in-image path.
RUN rm -f public/storage \
    && ln -s /var/www/html/storage/app/public /var/www/html/public/storage

RUN chown -R www-data:www-data /var/www/html/storage \
    /var/www/html/bootstrap/cache

COPY docker/nginx.conf /etc/nginx/sites-available/default
COPY docker/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
# Must be loaded after the image's default www.conf so it takes precedence.
COPY docker/php-fpm.conf /usr/local/etc/php-fpm.d/zz-buynow.conf

EXPOSE 10000

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
